Traceback (most recent call last):
  File "/home/jip/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/jip/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jip/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jip/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/jip/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jip/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/jip/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jip/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.figure(figsize=(12, 6))
sns.kdeplot(data=dp, x='winner_age', hue='gender', palette='coolwarm', fill=True)
plt.title('Dichtheid van Leeftijd per Geslacht')
plt.xlabel('Leeftijd')
plt.ylabel('Dichtheid')
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 2[0m
[1;32m      1[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m12[39m, [38;5;241m6[39m))
[0;32m----> 2[0m sns[38;5;241m.[39mkdeplot(data[38;5;241m=[39m[43mdp[49m, x[38;5;241m=[39m[38;5;124m'[39m[38;5;124mwinner_age[39m[38;5;124m'[39m, hue[38;5;241m=[39m[38;5;124m'[39m[38;5;124mgender[39m[38;5;124m'[39m, palette[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcoolwarm[39m[38;5;124m'[39m, fill[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m      3[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mDichtheid van Leeftijd per Geslacht[39m[38;5;124m'[39m)
[1;32m      4[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mLeeftijd[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'dp' is not defined
NameError: name 'dp' is not defined

